##  PythonClass 07 - Usage of Numpy Library

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, 
and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

### What is Array ?

- Array is a data structure that stores values of same data type. 

- Python List can contain values of divverent data type.

- Arrays in python can only contain values corresponding to same data type


In [ ]:
#How to import a library in python
#pip install numpy


In [1]:
import numpy as np

In [2]:
simple_list = [10,15,20,25,30,35,40,50]  #simple 8-element list

In [3]:
arr1=np.array(simple_list)

In [4]:
print(arr1)

[10 15 20 25 30 35 40 50]


In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape   #1D array

(8,)

In [7]:

## Multinested array
simple_list1=[10,15,20,25,30]
simple_list2=[90,80,70,60,50]
simple_list3=[20,40,60,80,100]

arr_3D=np.array([simple_list1,simple_list2,simple_list3])

In [8]:
print(arr_3D)

[[ 10  15  20  25  30]
 [ 90  80  70  60  50]
 [ 20  40  60  80 100]]


In [9]:
#Checking the shape of an array
arr_3D.shape

(3, 5)

In [10]:
arr_3D.reshape(5,3)  #Total elements should be same 5*3 = 15

array([[ 10,  15,  20],
       [ 25,  30,  90],
       [ 80,  70,  60],
       [ 50,  20,  40],
       [ 60,  80, 100]])

In [11]:
arr_3D.reshape(15,1) # 1D array #Total elements should be same 5*3 = 15

array([[ 10],
       [ 15],
       [ 20],
       [ 25],
       [ 30],
       [ 90],
       [ 80],
       [ 70],
       [ 60],
       [ 50],
       [ 20],
       [ 40],
       [ 60],
       [ 80],
       [100]])

In [12]:
arr_3D.reshape(5,4) #Give an error

ValueError: cannot reshape array of size 15 into shape (5,4)

## Indexing in Numpy

In [ ]:
## How will you access the array element in numpy ??

In [13]:
arr_3D

array([[ 10,  15,  20,  25,  30],
       [ 90,  80,  70,  60,  50],
       [ 20,  40,  60,  80, 100]])

In [14]:
arr_3D[:,:]

array([[ 10,  15,  20,  25,  30],
       [ 90,  80,  70,  60,  50],
       [ 20,  40,  60,  80, 100]])

In [15]:
#Suppose we need slice of Row 1 & Row2,Column 1 &2 like this   [10, 15],
                                               #               [90, 80]  , Then ?

arr_3D[0:2,0:2]

array([[10, 15],
       [90, 80]])

In [ ]:
#Suppose we need slice of Row 2 & Row3,Column 1 &2 like this   [90, 80],
       #                                                       [20, 40]  , Then ?

In [16]:
arr_3D[1:,:2]

array([[90, 80],
       [20, 40]])

### Some inbuilt numpy functions

In [20]:
arr1 = np.arange(0,10,dtype=int)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr2 = np.arange(0,10,step =2)
arr2

array([0, 2, 4, 6, 8])

In [22]:
arr3 = np.linspace(1,10,50)
arr3

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [25]:
arr_ex=np.random.randn(4,4)
arr_ex

array([[ 2.37549588, -0.58852958, -0.61939056,  1.1130462 ],
       [ 1.32773885,  0.09129116,  1.1920036 , -0.34753346],
       [ 0.79421137, -0.95725932,  0.50567614,  0.62885417],
       [ 1.18402583, -0.7876432 ,  0.45418206,  0.76473455]])

In [26]:
## Numpy Copy Function

arr2 = arr1.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#Random Function
arr_Random=np.random.randn(4,4)
arr_Random

array([[ 0.58818118, -0.7796197 , -2.07857035, -1.74316742],
       [-0.64048191, -0.50554735, -0.08358382, -0.19274884],
       [-0.8744487 , -2.05159972, -0.32965623,  0.0421718 ],
       [ 1.47900675,  0.51624212,  0.10583682, -0.23238993]])

In [30]:
## Builtin Functions mostly used in EDA are:

val =2

arr1[arr1<val]

array([0, 1])

In [31]:
arr1[arr1>val]

array([3, 4, 5, 6, 7, 8, 9])

In [32]:
arr1[arr1==val]

array([2])

In [33]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr1[3:]=100
arr1

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])